# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ad_tacker.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Window(object):
    def setupUi(self, Login_Window):
        Login_Window.setObjectName("Login_Window")
        Login_Window.resize(925, 757)
        Login_Window.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        Login_Window.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Login_Window)
        self.widget.setGeometry(QtCore.QRect(19, 29, 891, 701))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(470, 80, 320, 535))
        self.label.setStyleSheet("background-color: rgba(255,255,255,255);\n"
"border-radius: 10px")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(90, 65, 390, 565))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98, 112, 255), stop:1 rgba(255, 107, 107, 255));\n"
"border-radius: 10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.Log_in = QtWidgets.QLabel(self.widget)
        self.Log_in.setGeometry(QtCore.QRect(550, 130, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.Log_in.setFont(font)
        self.Log_in.setStyleSheet("color: rgba(0,0,0,200);")
        self.Log_in.setAlignment(QtCore.Qt.AlignCenter)
        self.Log_in.setObjectName("Log_in")
        self.User_Name = QtWidgets.QLineEdit(self.widget)
        self.User_Name.setGeometry(QtCore.QRect(510, 280, 255, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.User_Name.setFont(font)
        self.User_Name.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.User_Name.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,200);\n"
"padding-bottom: 7px;")
        self.User_Name.setText("")
        self.User_Name.setObjectName("User_Name")
        self.Password = QtWidgets.QLineEdit(self.widget)
        self.Password.setGeometry(QtCore.QRect(510, 340, 255, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Password.setFont(font)
        self.Password.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,200);\n"
"padding-bottom: 7px;")
        self.Password.setMaxLength(16)
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.Login_Button = QtWidgets.QPushButton(self.widget)
        self.Login_Button.setGeometry(QtCore.QRect(500, 450, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Login_Button.setFont(font)
        self.Login_Button.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: rgba(85,98,112,255);\n"
"    color: rgba(255,255,255,200);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(255,107,107,255);\n"
"    background-position: calc(100% - 10px);\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: rgba(255,107,107,255)\n"
"}")
        self.Login_Button.setObjectName("Login_Button")
        self.forget_password = QtWidgets.QLabel(self.widget)
        self.forget_password.setGeometry(QtCore.QRect(500, 410, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.forget_password.setFont(font)
        self.forget_password.setStyleSheet("color: rgba(0, 0, 0, 200);")
        self.forget_password.setAlignment(QtCore.Qt.AlignCenter)
        self.forget_password.setObjectName("forget_password")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(110, 80, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(62, 62, 62);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(90, 350, 381, 271))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(100)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgba(255,107,107,255);\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(400, 60, 71, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.closeButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.closeButton_2.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.closeButton_2.setFont(font)
        self.closeButton_2.setStyleSheet("QPushButton#minButton{\n"
"    background-color: rgba(85,98,112,255);\n"
"    color: rgba(255,255,255,200);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton { background-color: transparent; border: 0px; color:rgb(255, 255, 255, 200); }\n"
"\n"
"QPushButton#minButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(255,107,107,255);\n"
"    background-position: calc(100% - 10px);\n"
"}\n"
"\n"
"QPushButton#minButton:hover{\n"
"     color: rgba(0,0,0);\n"
"}")
        self.closeButton_2.setObjectName("closeButton_2")
        self.gridLayout.addWidget(self.closeButton_2, 1, 0, 1, 1)
        self.closeButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.closeButton.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.closeButton.setFont(font)
        self.closeButton.setMouseTracking(False)
        self.closeButton.setStyleSheet("QPushButton#minButton{\n"
"    background-color: rgba(85,98,112,255);\n"
"    color: rgba(255,255,255,200);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton { background-color: transparent; border: 0px; color:rgb(255, 255, 255, 200); }\n"
"\n"
"QPushButton#closeButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(255,107,107,255);\n"
"    background-position: calc(100% - 10px);\n"
"}\n"
"\n"
"QPushButton#closeButton:hover{\n"
"    color: rgba(255,107,107,255);\n"
"}")
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 1, 1, 1, 1)
        self.resgister_new_user = QtWidgets.QLabel(self.widget)
        self.resgister_new_user.setGeometry(QtCore.QRect(500, 520, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.resgister_new_user.setFont(font)
        self.resgister_new_user.setStyleSheet("color: rgba(0, 0, 0, 200);")
        self.resgister_new_user.setAlignment(QtCore.Qt.AlignCenter)
        self.resgister_new_user.setObjectName("resgister_new_user")

        self.retranslateUi(Login_Window)
        QtCore.QMetaObject.connectSlotsByName(Login_Window)

    def retranslateUi(self, Login_Window):
        _translate = QtCore.QCoreApplication.translate
        Login_Window.setWindowTitle(_translate("Login_Window", "Form"))
        self.Log_in.setText(_translate("Login_Window", "Log In"))
        self.User_Name.setPlaceholderText(_translate("Login_Window", " User Name"))
        self.Password.setPlaceholderText(_translate("Login_Window", " Password"))
        self.Login_Button.setText(_translate("Login_Window", "Log In"))
        self.forget_password.setText(_translate("Login_Window", "Forget your User Name or Password?"))
        self.label_5.setText(_translate("Login_Window", "AD-Tacker"))
        self.label_6.setText(_translate("Login_Window", "▒▒▒▒"))
        self.closeButton_2.setText(_translate("Login_Window", "–"))
        self.closeButton.setText(_translate("Login_Window", "x"))
        self.resgister_new_user.setText(_translate("Login_Window", "Register as a New User"))
