# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ad_tacker_register.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_Register(object):


    def registerfuntion(self):
        user = self.username.text()
        password = self.password.text()
        confirm_password = self.confirm_password.text()

        if len(password) == 0 or len(user) == 0 or len(confirm_password)==0:
                self.Error.setText("Please enter all the information") 

        elif password != confirm_password:
                self.Error.setText("Please enter correct password") 

    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(925, 757)
        Register.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        Register.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Register)
        self.widget.setGeometry(QtCore.QRect(19, 29, 891, 701))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(470, 80, 320, 535))
        self.label.setStyleSheet("background-color: rgba(255,255,255,255);\n"
"border-radius: 10px")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(90, 65, 390, 565))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98, 112, 255), stop:1 rgba(255, 107, 107, 255));\n"
"border-radius: 10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.register_2 = QtWidgets.QLabel(self.widget)
        self.register_2.setGeometry(QtCore.QRect(540, 130, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.register_2.setFont(font)
        self.register_2.setStyleSheet("color: rgba(0,0,0,200);")
        self.register_2.setAlignment(QtCore.Qt.AlignCenter)
        self.register_2.setObjectName("register_2")
        self.username = QtWidgets.QLineEdit(self.widget)
        self.username.setGeometry(QtCore.QRect(510, 240, 255, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username.setFont(font)
        self.username.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.username.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,200);\n"
"padding-bottom: 7px;")
        self.username.setText("")
        self.username.setMaxLength(30)
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(510, 300, 255, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,200);\n"
"padding-bottom: 7px;")
        self.password.setText("")
        self.password.setMaxLength(16)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.Registerbutton = QtWidgets.QPushButton(self.widget)
        self.Registerbutton.clicked.connect(self.registerfuntion)
        self.Registerbutton.setGeometry(QtCore.QRect(500, 450, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Registerbutton.setFont(font)
        self.Registerbutton.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: rgba(85,98,112,255);\n"
"    color: rgba(255,255,255,200);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(255,107,107,255);\n"
"    background-position: calc(100% - 10px);\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: rgba(255,107,107,255)\n"
"}")
        self.Registerbutton.setObjectName("Registerbutton")
        self.login_page = QtWidgets.QLabel(self.widget)
        self.login_page.setGeometry(QtCore.QRect(500, 530, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.login_page.setFont(font)
        self.login_page.setStyleSheet("color: rgba(0, 0, 0, 200);")
        self.login_page.setAlignment(QtCore.Qt.AlignCenter)
        self.login_page.setObjectName("login_page")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(110, 80, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(62, 62, 62);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(90, 350, 381, 271))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(100)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgba(255,107,107,255);\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.confirm_password = QtWidgets.QLineEdit(self.widget)
        self.confirm_password.setGeometry(QtCore.QRect(510, 360, 255, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confirm_password.setFont(font)
        self.confirm_password.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,200);\n"
"padding-bottom: 7px;")
        self.confirm_password.setMaxLength(16)
        self.confirm_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_password.setObjectName("confirm_password")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(400, 60, 71, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.closeButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.closeButton_2.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.closeButton_2.setFont(font)
        self.closeButton_2.setStyleSheet("QPushButton#minButton{\n"
"    background-color: rgba(85,98,112,255);\n"
"    color: rgba(255,255,255,200);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton { background-color: transparent; border: 0px; color:rgb(255, 255, 255, 200); }\n"
"\n"
"QPushButton#minButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(255,107,107,255);\n"
"    background-position: calc(100% - 10px);\n"
"}\n"
"\n"
"QPushButton#minButton:hover{\n"
"     color: rgba(0,0,0);\n"
"}")
        self.closeButton_2.setObjectName("closeButton_2")
        self.gridLayout.addWidget(self.closeButton_2, 1, 0, 1, 1)
        self.closeButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.closeButton.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.closeButton.setFont(font)
        self.closeButton.setMouseTracking(False)
        self.closeButton.setStyleSheet("QPushButton#minButton{\n"
"    background-color: rgba(85,98,112,255);\n"
"    color: rgba(255,255,255,200);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton { background-color: transparent; border: 0px; color:rgb(255, 255, 255, 200); }\n"
"\n"
"QPushButton#closeButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(255,107,107,255);\n"
"    background-position: calc(100% - 10px);\n"
"}\n"
"\n"
"QPushButton#closeButton:hover{\n"
"    color: rgba(255,107,107,255);\n"
"}")
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 1, 1, 1, 1)
        self.login_page_2 = QtWidgets.QLabel(self.widget)
        self.login_page_2.setGeometry(QtCore.QRect(520, 400, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)


        self.Error.setFont(font)
        self.Error.setStyleSheet("color: rgba(255,107,107,255);")
        self.Error.setText("")
        self.Error.setObjectName("login_page_2")

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Form"))
        self.register_2.setText(_translate("Register", "Register"))
        self.username.setPlaceholderText(_translate("Register", " User Name"))
        self.password.setPlaceholderText(_translate("Register", " Enter Password"))
        self.Registerbutton.setText(_translate("Register", "Register"))
        self.login_page.setText(_translate("Register", "Already have an account"))
        self.label_5.setText(_translate("Register", "AD-Tacker"))
        self.label_6.setText(_translate("Register", "▒▒▒▒"))
        self.confirm_password.setPlaceholderText(_translate("Register", " Confirm Enter Password"))
        self.closeButton_2.setText(_translate("Register", "–"))
        self.closeButton.setText(_translate("Register", "x"))
